name: 'Hello World'
description: 'Greet someone'
inputs:
    profile:
      required: true
      description: "The name of the publish profile to use. Must match the name (without extension) of a publish profile in the Properties/PublishProfiles folder of the project."
    variant:
      required: false
      default: "default"
      description: "The 'variant' of the build to be run - this is used when testing different auth modes for the same publish profile, for example."
    selfContained:
      default: "[true, false]"
      required: false
      description: "The values of self-contained to test this variant with. Some variants don't work with SC/FDD builds, so use this to control which ones are tested. Valid values are 'true', 'false', or '[true, false]' to test both."

runs:
  using: "composite"
  steps:
    - name: Publish self contained
      shell: pwsh
      if: ${{ contains(fromJson(inputs.selfContained), true) }} && always()
      run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=${{ inputs.profile }} --self-contained true -p VersionSuffix=${{ inputs.variant }}-sc /bl
    
    - name: Archive binlog self-contained
      uses: actions/upload-artifact@v3
      if: ${{ contains(fromJson(inputs.selfContained), true) }} && always()
      with:
          name: ${{ inputs.profile}}-${{ inputs.variant }}-sc.binlog
          path: msbuild.binlog
    
    - name: Publish framework dependent
      shell: pwsh
      if: ${{ contains(fromJson(inputs.selfContained), false) }} && always()
      run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=${{ inputs.profile }} --self-contained false -p VersionSuffix=${{ inputs.variant }}-fdd /bl
    
    - name: Archive binlog self-contained
      uses: actions/upload-artifact@v3
      if: ${{ contains(fromJson(inputs.selfContained), false) }} && always()
      with:
          name: ${{ inputs.profile}}-${{ inputs.variant }}-fdd.binlog
          path: msbuild.binlog