name: AOT Example

on:
  push:
  workflow_dispatch:

env:
  GITHUB_USERNAME: baronfel
  GITHUB_TOKEN: ${{ secrets.CONTAINER_PUSH_PAT }}



jobs:
  aot:
    strategy:
      matrix:
        sdkflavor: [alpine-aot, jammy-aot]
        arch: [amd64, arm64v8]
        include:
        - sdkflavor: jammy-aot
          installcommand: apt install docker-ce
          runtimeflavor: jammy-chiseled
        - sdkflavor: alpine-aot
          runtimeflavor: alpine
          installcommand: apk add docker

    name: "Build AOT Console App for ${{ matrix.sdkflavor }}-${{ matrix.arch }} to ${{ matrix.runtimeflavor }}-${{ matrix.arch }}"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      if: matrix.arch != 'amd64'
      uses: docker/setup-buildx-action@v2
    - name: Set up QEMU
      if: matrix.arch != 'amd64'
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64,arm'
    - name: Get the code
      uses: actions/checkout@v2
    - name: build the app AOT-style
      run: |
        docker run --rm --pull=always \
          -v $(pwd)/src:/src \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -w /src/aot-sample \
          mcr.microsoft.com/dotnet/nightly/sdk:8.0-${{ matrix.sdkflavor }}-${{matrix.arch}} \
          sh -c "
            ${{matrix.installcommand}} && \
            dotnet publish /t:PublishContainer \
              -p ContainerBaseImage=mcr.microsoft.com/dotnet/runtime-deps:8.0-${{matrix.runtimeflavor}}-${{matrix.arch}} \
              -p ContainerImageTag=${{matrix.runtimeflavor}}-${{matrix.arch}} \
          "
    - name: run the just-built container
      run: |
          docker run --rm aot-sample:${{matrix.runtimeflavor}}-${{matrix.arch}}
    - name: inspect the just-built container
      run: | 
        docker history aot-sample:${{matrix.runtimeflavor}}-${{matrix.arch}} --format "{{.ID}}: {{.Size}}"
