name: AOT Example

on:
  push:
  workflow_dispatch:

env:
  GITHUB_USERNAME: baronfel
  GITHUB_TOKEN: ${{ secrets.CONTAINER_PUSH_PAT }}

jobs:
  aot:
    name: "Build AOT Console App"
    runs-on: ubuntu-latest
    steps:
    - name: Get the code
      uses: actions/checkout@v2
    - name: build the app AOT-style
      run: |
        docker run --rm --pull=always \
          -v $(pwd)/src:/src \
          -v /var/run/docker.sock:/var/run/docker.sock \
          mcr.microsoft.com/dotnet/nightly/sdk:8.0-alpine-aot \
          sh -c "
            apk add docker && \
            cd ./src/aot-sample && \
            dotnet publish /t:PublishContainer /p:ContainerBaseImage=mcr.microsoft.com/dotnet/runtime-deps:8.0-alpine --use-current-runtime -bl \
          "
    - name: run the just-built container
      run: |
          docker run --rm aot-sample:latest
    - name: inspect the just-built container
      run: | 
        docker history aot-sample:latest --format "{{.ID}}: {{.Size}}"
    - name: Upload binlog
      uses: actions/upload-artifact@v3
      with:
          path: src/aot-sample/msbuild.binlog
          name: msbuild.binlog
