name: Containerize ASP.NET Core application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
      - name: Docker Login
        uses: actions-hub/docker/login@master
        env:
          DOCKER_REGISTRY_URL: ghcr.io
          DOCKER_USERNAME: baronfel
          DOCKER_PASSWORD: ${{ secrets.CONTAINER_PUSH_PAT }}
      - name: Build
        run: dotnet build --os linux --arch x64 --configuration Release
        env:
          GITHUB_USERNAME: baronfel
          GITHUB_TOKEN: ${{ secrets.CONTAINER_PUSH_PAT }}
      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=DefaultContainer
      - name: Tag built container with GitHub Registry url
        uses: actions-hub/docker/cli@master
        with:
          args: tag sdk-container-demo:1.0.0 ghcr.io/baronfel/sdk-container-demo:latest
      - name: Push built container to GitHub Registry
        uses: actions-hub/docker/cli@master
        with:
          args: push ghcr.io/baronfel/sdk-container-demo:latest