name: Containerize

on:
  push:
  workflow_dispatch:

env:
  GITHUB_USERNAME: baronfel
  GITHUB_TOKEN: ${{ secrets.CONTAINER_PUSH_PAT }}

jobs:

  azure-admin-credentials:
    name: Azure Container Registry - admin credentials
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Log in to container registry
        uses: azure/docker-login@v1
        with:
          login-server: sdkcontainerdemo.azurecr.io
          username: sdkcontainerdemo
          password: ${{ secrets.ACR_PAT }}

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=azure

  azure-token-credentials:
    name: Azure Container Registry - token credentials
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Log in to container registry
        uses: azure/docker-login@v1
        with:
          login-server: sdkcontainerdemo.azurecr.io
          username: sdk-container-demo-token
          password: ${{ secrets.ACR_TOKEN_PASSWORD }}

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=azure -p ContainerImageTag=token-credential

  azure-ad-credentials:
    name: Azure Container Registry - AD OIDC credentials
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "DOCKER_TOKEN=$(az acr login --name sdkcontainerdemo --expose-token --output tsv --query accessToken)" >> $GITHUB_ENV

      - name: Log in to container registry
        uses: azure/docker-login@v1
        with:
          login-server: sdkcontainerdemo.azurecr.io
          username: 00000000-0000-0000-0000-000000000000
          password: ${{ env.DOCKER_TOKEN }}

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=azure -p ContainerImageTag=ad-credential

  github:
    name: GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Log in to container registry
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: baronfel
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=github

  github-raw:
    name: GitHub Package Registry - Raw CLI calls
    runs-on: ubuntu-latest
    env:
      SDK_CONTAINER_REGISTRY_CHUNKED_UPLOAD: true
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Log in to container registry via docker CLI
        run: echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u baronfel --password-stdin

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=github

  aws:
    name: AWS Elastic Container Registry
    runs-on: ubuntu-latest
    env:
      SDK_CONTAINER_REGISTRY_CHUNKED_UPLOAD: true
      SDK_CONTAINER_REGISTRY_CHUNKED_UPLOAD_SIZE_BYTES: 1000
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=aws /bl

      - name: Archive binlog
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: aws.binlog
          path: msbuild.binlog

  gitlab:
    name: GitLab Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Log in to container registry
        uses: azure/docker-login@v1
        with:
          login-server: registry.gitlab.com
          username: chet.husk
          password: ${{ secrets.GITLAB_CONTAINER_PAT }}

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=gitlab /bl

      - name: Archive binlog
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: gitlab.binlog
          path: msbuild.binlog

  gcp:
    name: Google Cloud Artifact Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      # Setup gcloud CLI
      - uses: google-github-actions/auth@main
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: gcloud auth configure-docker us-south1-docker.pkg.dev

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=gcp -bl

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: GCP.binlog
          path: msbuild.binlog

  localdocker:
    name: Local Docker Daemon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=localdocker -bl

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: localdocker.binlog
          path: msbuild.binlog

  localdocker-trimmedandchiseled:
    name: Local Docker Daemon, Chiseled Ubuntu container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=localdocker-trimmedandchiseled -bl --self-contained true

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: localdocker-trimmedandchiseled.binlog
          path: msbuild.binlog

  localpodman:
      name: Local Podman installation
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v2

        - name: Publish
          run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=localpodman -bl

        - name: List images (podman)
          run: podman image list --all

        - name: List images (docker)
          run: docker image list --all

        - name: Archive code coverage results
          uses: actions/upload-artifact@v3
          with:
            name: localpodman.binlog
            path: msbuild.binlog

  dockerhub:
    name: Push to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Log in to container registry
        uses: azure/docker-login@v1
        with:
          login-server: registry-1.docker.io
          username: chusk3
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=dockerhub -bl

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: dockerhub.binlog
          path: msbuild.binlog

  quay:
    name: Push to Quay.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Log in to container registry
        uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: baronfel
          password: ${{ secrets.QUAY_PAT }}

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=quay -bl

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: quay.binlog
          path: msbuild.binlog

  harbor:
    name: Push to Harbor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Log in to container registry
        uses: azure/docker-login@v1
        with:
          login-server: demo.goharbor.io
          username: "robot$net-sdk-container-demo+push-daemon"
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=harbor -bl

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: harbor.binlog
          path: msbuild.binlog