name: Containerize - GitHub

on: [push]

jobs:
  github:
    name: GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2

      - name: Log in to container registry
        uses: azure/docker-login@v1
        env:
          DOCKER_CONFIG: '/home/runner/.docker'
        with:
          login-server: ghcr.io
          username: baronfel
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=github